---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: $K8S_DEPLOYMENT_NAME-$TARGET_ROLE
  labels:
    resourcetype: cartridge
    name: $K8S_DEPLOYMENT_NAME
spec:
  replicas: $REPLICAS
  selector:
    matchLabels:
      name: $K8S_DEPLOYMENT_NAME
  template:
    metadata:
      labels:
        name: $K8S_DEPLOYMENT_NAME
        role: $TARGET_ROLE
    spec:
      automountServiceAccountToken: false
      imagePullSecrets:
        - name: nodecred
      containers:
      - name: $K8S_DEPLOYMENT_NAME
        image: $IMG_NAME:$IMG_TAG
        imagePullPolicy: "Always"
        ports:
         - containerPort: 5000
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001

---
apiVersion: v1
kind: Service
metadata:
  name: $K8S_DEPLOYMENT_NAME-$TARGET_ROLE-test
  labels:
    name: $K8S_DEPLOYMENT_NAME-service
    env: dev
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 5000
  selector:
    name: $K8S_DEPLOYMENT_NAME
    role: $TARGET_ROLE
